export default {
  GAME_REQUEST: "GAME_POST_REQUEST",
  GAME_REQUEST_FAILURE: "GAME_REQUEST_FAILURE",
  GAME_CLEAR_BOARD: "GAME_CLEAR_BOARD",

  GAME_POST_NEW_GAME_SAGA: "GAME_POST_NEW_GAME_SAGA",
  GAME_POST_NEW_GAME_SUCCESS: "GAME_POST_NEW_GAME_SAGA_SUCCESS",

  GAME_POST_PLAY_SAGA: "GAME_POST_PLAY_SAGA",
  GAME_POST_PLAY_SUCCESS: "GAME_POST_PLAY_SUCCESS",

  GAME_GET_GENERAL_SAGA: "GAME_GET_GENERAL_SAGA",
  GAME_GET_GENERAL_SUCCESS: "GAME_GET_GENERAL_SUCCESS",
};
